### ISSUE TITLE
undefined: execCommand in host_id_bsd.go

### ISSUE THREAD

**Issue by donbowman** [open-telemetry/opentelemetry-go#4076]
### Description

presumably this is caused by https://github.com/open-telemetry/opentelemetry-go/pull/4015

 go.opentelemetry.io/otel/sdk/resource
../../../go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.15.1/resource/host_id_bsd.go:21:15: undefined: execCommand
../../../go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.15.1/resource/host_id_bsd.go:22:15: undefined: readFile

this is compiled from amd64 linux to freebsd as:

CGO_ENABLED=0 GOOS=freebsd GOARCH=amd64 go build -ldflags "-s -w" -installsuffix cgo -o mybin

### Environment

- ubuntu 22.04
- amd64
- go1.20.1
- opentelemetry-go version: 1.15.1

### Steps To Reproduce

my code doesn't call this directly.
I use 
```
go mod why go.opentelemetry.io/otel/sdk
# go.opentelemetry.io/otel/sdk
git.agilicus.com/platform/secure-exposed-agent/pkg/httpproxy
git.agilicus.com/platform/opa-istio-plugin/v4/pkg/apiauthz
git.agilicus.com/platform/opa-istio-plugin/v4/internal
github.com/open-policy-agent/opa/plugins
go.opentelemetry.io/otel/sdk/trace
go.opentelemetry.io/otel/sdk/resource
go.opentelemetry.io/otel/sdk
```

### Expected behavior

It to compile (as it did in 1.14.0)

**Comment by pellared** [comment]
I am sorry for introducing the bug. I am working on a fix. I will also explore the possibility of running the build on multiple GOOS.
