### ISSUE TITLE
Use UnaryServerInterceptor with otel.tracer

### ISSUE THREAD

**Issue by jumpyBiggins** [open-telemetry/opentelemetry-go#1495]
I was an older version of otel(v0.11) and I was using the tracer in a UnaryServerInterceptor. 
after the update to v0.16.0

the below code does not work because tracer does not implement the `Apply` method
```
tracer := otel.Tracer("testTracer")
opts := grpc.ChainUnaryInterceptor(otelgrpc.UnaryServerInterceptor(tracer))
```

what is the workaround for this? 

thanks.
